int a,b,c,d
a = int(input())
b = int(input())
c = int(input())
if(a%2 == 0 && b%2 == 0)
  print(even numbers)
elif(a%2 == 1 && b%2 == 1)
  print(even numbers) 
if((a%2 == 0 && b%2 == 1)||(a%2 == 1 && b%2 == 0))
  print(even and odd numbers)
